import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './provider'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bgImg`}>
        <Providers>
        <Image src="/bg2.png" alt='bg' width={5760} height={4096} className='absolute top-0 left-0 w-full h-full z-2' />
        {children}
        </Providers>
        </body>
    </html>
  )
}
